#+STARTUP: overview
#+STARTUP: indent

* Vienna - [[https://csh.ac.at/][Complexity Science Hub]]
** [[https://csh.ac.at/research/research-topic/social-complexity-collapse/][Social Complexity & Collapse]]
Ha a che fare con *Storia*.
*** [[https://peterturchin.com/][Peter Turchin]] [[https://scholar.google.com/citations?hl=en&user=W0C05zIAAAAJ&view_op=list_works&sortby=pubdate][(scholar]])
È il capo. Super importante ([[https://en.wikipedia.org/wiki/Peter_Turchin][wikipedia]], h-index 75), ha /fondato/ questa cosa che chiama /cliodynamics/, fa database di storia/archeologia.

Nel gruppo ci sta altra gente:
*** [[https://mariadelriochanona.info/][Maria del Rio-Chanona]] ([[https://scholar.google.com/citations?user=HwK5iiEAAAAJ&hl=en][scholar]])
Sta in realtà ad [[https://profiles.ucl.ac.uk/97689-maria-del-riochanona][UCL]]. È una matematica, fa cose di questo tipo ma usando molto AI, NLP. Studia tipo impatto di AI. [[https://ucl-epsrc-dtp.github.io/2026-27-project-catalogue/projects/2531bd1646.html][Sta cercando un dottorato]] per AI/Multi-agent systems.
Sembra faccia tipo come la storia si sta evolvendo con AI. Una cosa del genere.
*** [[https://csh.ac.at/james-bennett/][James Bennett]] (scholar non si trova...)
Non si capisce bene che fa, ma è interessante perché ha tipo lanciato lui il netflix prize (????)

Poi ci stanno dei
*** PhD
- [[https://csh.ac.at/harry-fox/][Harry Fox]] è un tipo, applica concetti della fisica a /economia, sociologia e psicologia di gruppo/. Interessante...
** [[https://csh.ac.at/research/research-topic/collective-minds/][Collective Minds]]
Questo è forse anche più interessante. La descrizione è carina, la incollo...
:Descrizione:
Currently, we are lacking a solid scientific paradigm for studying
collective adaptation. Instead, its intertwined cognitive and social
dimensions have been studied in relatively isolated disciplines. We
bring these dimensions together in computational models grounded in
real-world data on cognition and sociality.
:END:
Fanno (mi sembra) cose al limite tra psicologia, sociologia e scienze dure.

Ci sono 2 capi
*** [[https://www.olssonresearch.com/][Henrik Olsson]] ([[https://scholar.google.com/citations?user=XKwkvxcAAAAJ&hl=en][scholar]])
È psicologo, ma sembra essersi avvicinato abbastanza a ricerca
operativa. Sembra essere piuttosto interessante - approfondisci!
*** TODO Approfondisci questo sopra
*** PhD
- [[https://scholar.google.com/citations?hl=de&user=9FQdKwwAAAAJ&view_op=list_works&sortby=pubdate][Jula Lühring]] sembra abbastanza interessante - è PhD ma già ha un po'
  di citazioni ecc. Fa comunicazione, e cose su diffusione della
  disinformazione
* Sapienza
** [[https://chimera.roma1.infn.it/][Chimera]] (fisica)
Questo in realtà non è ben chiaro se esistono ancora.
Sembrano molto molto fisici e ci sta Parisi di mezzo - quindi pericolo.

Vabbè fanno moltissimo fisica... Un po' troppo.
*** [[https://sites.google.com/uniroma1.it/irene-giardina][Irene Giardina]] ([[https://scholar.google.it/citations?user=lPBjU44AAAAJ&hl=it][scholar]])
Praticamente fa fisica applicata a sistemi viventi tipo, e /collective behavior/ loro.
Forse non molto interessante, ma abbiamo stesso cognome...
Sta nel gruppo [[https://www.isc.cnr.it/groups/cobbs/][Collective Behaviour in Biological Systems]] infatti.
** [[https://cdcs.di.uniroma1.it/][Center for Data Science and Complexity for Society]] (informatica)
Sicuramente fanno parecchio su polarizzazione. Che è interessante comunque.
Poi sembra facciano anche cose su LLM e forse sentiment analysis (che vorrei fare un po' meno).

Sembra che siano piuttosto applicati, forse un po' troppo. Mi fa un po' paura questa cosa della divulgazione.

/Where data meets complexity, and science informs society./ Boh

Il boss è
*** [[https://walterquattrociocchi.site.uniroma1.it/][Walter Quattrociocchi]] ([[https://scholar.google.it/citations?user=_OCIc6UAAAAJ&hl=en][scholar]])
È abbastanza uno importante, ha scritto libri ecc.
Fa ogni paper del gruppo. Ha fatto fortuna con covid e disinformazione.

* Ca' Foscari
** [[https://www.unive.it/data/11644/][Research Institute for Complexity]]
*** [[https://www.guidocaldarelli.com/][Guido Caldarelli]] ([[https://scholar.google.com/citations?user=RZid9X8AAAAJ&hl=it][scholar]], [[https://en.wikipedia.org/wiki/Guido_Caldarelli][wikipedia]])
Lui super importante. È fisico, ha studiato a Sapienza, PhD a SISSA, prof a IMT.
È direttore dell'[[https://www.isc.cnr.it/][istituto dei sistemi complessi al CNR]].
È molto interessante per il mix tra teorico ed applicato, che sembra giusto.
Il problema è che non posso scrivergli haha. Dovrebbe stare a Roma (CNR) però.
* Dauphine
Professori abilitati ad avere dottorati sono [[https://ecole-doctorale.dauphine.psl.eu/candidature/trouver-une-direction-de-these][qui]].
** [[https://www.lamsade.dauphine.fr/en/about-us/lamsade-in-brief.html][LAMSADE (Laboratoire d'Analyse et Modélisation des Systèmes et Aide à la Décision)]]
Questo è in origine centro di ricerca operativa, si è esteso a /aiuto alla decisione/.
Si possono trovare tante cose mi sa qui.
*** TODO André Rossi
*** [[https://www.lamsade.dauphine.fr/~lang/][Jérôme Lang]] ([[https://scholar.google.com/citations?hl=fr&user=cNgZXNcAAAAJ&view_op=list_works&sortby=pubdate][scholar]], [[https://fr.wikipedia.org/wiki/J%C3%A9r%C3%B4me_Lang][wikipedia]])
Ha taaante citazioni (h-index tipo 67), anche se è solo /directeur de recherche/.

È interessante: fa principalmente teoria del voto, ed intelligenza artificiale ma non statistica, precisa (a quanto sembra).

La cosa che fa si chiama tipo /computational social *choice*/.
#+begin_quote
/Social choice studies the behavior of different mathematical procedures (social welfare functions) used to combine individual preferences into a coherent whole/.

È tipo la scienza di come le società prendono decisioni ma, in contrasto alle scienze politiche,
prova a modellizzare processi ottimali piuttosto che a descrivere i processi attuali.

Nata da [[https://www.jstor.org/stable/j.ctt1nqb90][questo libro]] del 1951. Il libro è suuuper interessante!!
#+end_quote

È molto interessante l'impatto che la sua ricerca può potenzialmente avere sul mondo, sono *molto molto* interessato.
*** [[https://sites.google.com/site/ridalaraki/][Rida Laraki]] ([[https://scholar.google.com/citations?hl=fr&user=zwkQWEgAAAAJ&view_op=list_works&sortby=pubdate][scholar]])
Mi sa che in realtà sta in Marocco... Ma è abilitato a dirigere PhD a Dauphine (?).

Comunque è interessante: ha master e PhD in matematica (non so che matematica...), e fa teoria dei giochi, ricerca operativa e pure lui /social chioce/.

È molto famoso per questa un metodo di voto che ha inventato con [[https://en.wikipedia.org/wiki/Michel_Balinski][un matematico molto importante]], chiamato [[https://en.wikipedia.org/wiki/Majority_judgment][majority judgement]].
Questo sembra una cosa interessante, ma non interessantissima - non molto complessa probabilmente, anche se non ho letto il libro loro.

Comunque queste cose che presumono che tutti gli elettori siano razionali ecc non possono mai funzionare.
Addirittura lui ha fatto un'estensione di questo sistema che permette di esprimere /incertezza/ sulla valutazione del candidato.
Secondo me assolutamente nessuno userebbe questa incertezza.

*** [[https://www.lamsade.dauphine.fr/~moretti/][Stefano Moretti]] ([[https://scholar.google.com/citations?hl=it&user=wQOB0vkAAAAJ&view_op=list_works&sortby=pubdate][scholar]])
Scrivigli perché è molto interessante. Lavora abbastanza in teoria dei giochi (ha fatto tipo 2 dottorati in teoria dei giochi).
Pubblica in giornali abbastanza sfigati sembra.
Ha un approccio abbastanza formale e lavora con ordini.

*** [[https://sites.google.com/site/julienlesca/home][Julien Lesca]] ([[https://scholar.google.com/citations?user=iNznokkAAAAJ&hl=fr][scholar]])
Interessante: è un informatico, e fa proprio cose di /decision science/ (se questo vuol dire qualche cosa).
Fa pure cose con grafi e ottimizzazione. Solo che pubblica poco, questa cosa non si capisce tanto.

Nota che, in [[https://www.ifaamas.org/Proceedings/aamas2022/pdfs/p687.pdf][questo paper]], dice che
#+begin_quote
We study a student-project allocation problem motivated by the real
procedure used at the computer science department of University
Paris-Dauphine. The institute (school, university) publishes a set
of PhD projects
#+end_quote
Questo è un po' strano (non mi risulta...). Forse glielo si può chiedere.
*** [[https://dauphine.psl.eu/recherche/cvtheque/profil/grigori-daniela][Daniela Grigori]] ([[https://scholar.google.com/citations?hl=fr&user=uOpbfVsAAAAJ&view_op=list_works&sortby=pubdate][scholar]])
Fa cose interessanti, anche se sembra un po' in decadenza.
È stata direttrice del LAMSADE fino al 2023.

Fa grafi e cose con processi aziendali.
È informatica, può essere interessante.
*** [[https://www.lamsade.dauphine.fr/~mlampis/][Michael Lampis]] ([[https://scholar.google.com/citations?user=x0XUqygAAAAJ&hl=en][scholar]])
È abbastanza un informatico puro (studia complessità asintotica e cose del genere),
ma la cosa interessante è che lavora molto con i grafi. Che sono abbastanza interessanti. Però praticamente non lavora su applicazioni.

Se gli scrivessi dovrei scrivergli ciao mi interessa quello che fai mi dici un applicazione?
*** Gente varia
Se serve gente che fa ottimizzazione discreta/lavora su grafi c'è di tutto:
[[https://dauphine.psl.eu/recherche/cvtheque/profil/aissi-hassene][Hassan Aissi]], [[https://dauphine.psl.eu/recherche/cvtheque/profil/bazgan-cristina][Cristina Bazgan]].
[[https://dauphine.psl.eu/recherche/cvtheque/profil/harutyunyan-ararat][Harutyunyan Ararat]] lavora su grafi in maniera molto teorica.

C'è pure parecchia gente che fa AI:
ad esempio, [[https://www.lamsade.dauphine.fr/~ychevaleyre/][Yann Chevaleyre]] ha un PhD aperto (in /robustness in AI/).
* Sciences po
Chiaramente qui è più difficile, sono estremamente nella parte qualitativa... Però forse qualcosa ci sta.
** [[https://www.sciencespo.fr/cdsp/en/][Centre for Socio-Political Data]]
Sono quelli che gestiscono dati in generale. Per quello che ho capito fanno diverse cose:
- Gestiscono tutta l'infrastuttura di sciences po (anche sito web?) (ma questo non è che sono proprio sicuro).
- Assistono la ricerca varia tramite produzione di dati (ci sono un sacco di questi /ingegneri di ricerca/).
- Fanno ricerca.

[[https://www.sciencespo.fr/cdsp/en/news/post-doctoral-researcher-in-historic-political-data-analysis-2-year-contract/][Stanno cercando un postdoc]], finanziato da Open AI (???). Sicuramente se volessero potrebbero prendere un PhD, ma mi sa che non vogliono qualcuno di solo scientifico.

In generale, hanno tutti background in scienze politiche tranne poche eccezioni.
[[https://www.sciencespo.fr/cdsp/en/who-are-we/team/][Qui]] c'è tutta la gente.

*** [[https://www.sciencespo.fr/cdsp/fr/qui-sommes-nous/equipe/mahendra-paipuri/][Mahendra Paipuri]] ([[https://scholar.google.com/citations?hl=en&user=6kCpWZ8AAAAJ&view_op=list_works&sortby=pubdate][scholar]])
Scrivigli assolutamente. Ha lavorato nel traffico ed ha pubblicato con Nikolas Geroliminis.
Ora non si capisce bene che fa (in realtà dice /dirige la squadra dei progetti numerici/, ma è strano dato che ha un dottorato comunque),
ma sta nella squadra.

Questo va raggiunto assolutamente.

*** [[https://www.emilianogrossman.eu/][Emiliano Grossman]] ([[https://scholar.google.com/citations?hl=en&user=mhVGOysAAAAJ&view_op=list_works&sortby=pubdate][scholar]])
È il capo del gruppo. Dalla ricerca che fa sembra faccia cose molto umanistiche, ma è comunque direttore del centro per i dati...

Fa ricerca su partiti, elezioni, ecc.

*** [[https://www.rovny.org/][Jan Rovny]] ([[https://scholar.google.fr/citations?hl=fr&user=ElGAc6MAAAAJ&view_op=list_works&sortby=pubdate][scholar]])
Lui sembra faccia un po' più ricerca con dati, anche se non sembra avere nessun'affiliazione con il CDSP
(nel sito dice che è affiliato ad un altro centro, il [[https://www.sciencespo.fr/centre-etudes-europeennes/en/][Centre for European Studies and Comparative Politics]]).

In effetti, fa ricerca sui partiti e la politica europea.

*** [[https://www.sciencespo.fr/centre-etudes-europeennes/en/directory/sattelmayer-luis/][Luis Sattelmayer]]
È un PhD, e lavora sul declino dei partiti tradizionali. La cosa interessante è che
/he primarily uses computational and experimental methods to examine party discourse and to find new ways of measuring party positions and party behavior/.

Non mi svolterà cose, ma magari ha contatti ecc.
* [[https://www.santannapisa.it/it][Sant'Anna]]
Il PhD si divide in 2: uno [[https://www.santannapisa.it/it/formazione/international-doctoral-programme-economics][in economia]], con scadenza il 15 aprile, ed [[https://www.santannapisa.it/it/formazione/phd][i restanti]], con scadenza 15 maggio.

A quanto pare questi sono quelli forti forti in economia dell'innovazione.

Quelli che scadono a maggio non sembrano molto interessanti, mentre quello in economia sembra una cosa figa.
Sarebbe super saggio parlare con qualcuno di economia. Il /Faculty Board/ (qualunque cosa voglia dire) sta [[https://www.santannapisa.it/it/coordinator-and-faculty-board-phd-economics][qui]].
** [[https://www.cafed.santannapisa.it/~giulio/][Giulio Bottazzi]]
Moolto carino!! È un fisico, il problema è che fa un po' finanza. Ma dice /economic geography/ (che è molto figo, lo scrive [[https://www.santannapisa.it/it/giulio-bottazzi][qui]]) e tante altre cose fighe.
** [[https://sites.google.com/view/giorgiofagiolo/home][Giorgio Fagiolo]] [[https://scholar.google.it/citations?user=B7N-yQIAAAAJ][(scholar)]]
Sembra uno importante, ma non ha posizioni particolari (è ordinario comunque).

La ricerca sembra parecchio interesante, fa molto numerico. È tipo statistico.

Ha lavorato a BETA magari conosce Nathalie (in realtà non so, BETA sembra una cosa grande proprio).

** [[https://sites.google.com/view/alessiomoneta][Alessio Moneta]] [[https://scholar.google.it/citations?user=ORWa37UAAAAJ&hl=it][(scholar)]]
Pure lui sembra strafigo.

È il responsabile del programma di PhD (che può essere un pro o un contro per scrivergli, sarà meno curioso ma più pertinente forse.

È filosofo (??), e fa cose super tecniche, causal inference.

** [[https://www.santannapisa.it/it/andrea-roventini][Andrea Roventini]]
Lui mi sa che è abbastanza economista classico. Dice però che i suoi interessi sono tipo
#+begin_quote
complex system analysis, agent-based computational economics...
#+end_quote
e poi tutte cose normali.

Ha scritto [[https://www.cambridge.org/core/elements/abs/agentbased-macroeconomics/B7016A5CEE59694A420AF51A1347F00E][un libro carino]] ed [[https://www.sciencedirect.com/science/article/abs/pii/S016518891000148X][un paper]] ([[https://d1wqtxts1xzle7.cloudfront.net/44382174/2008-21-libre.pdf?1459761754=&response-content-disposition=inline%3B+filename%3DSchumpeter_meeting_Keynes_A_policy_frien.pdf&Expires=1774441495&Signature=RMk1zWbIHnkgxQOoqEMCXKbCwqAe~qsOWhL5GGTwUWmPDkIUdmnt~~JBqmOWvdVLULI6GF5rJRpOsUTdqeQB~jCqyUULSXd1IGkBttuu9WENQug574YzjvmYBvTfUqy-aw~3ACttqF4eZl6~H0JBe8c0JunXPSon6GEKateMLjcIUMZDrllOrtxg6ykcZiPCA0dxCQJLP9xBAibRcC-gYG-t9lh~eMJ3HQvZrLpBl1KWno8oWJuYeMcUdFgbBZTJivhuxLSkPhYy5H1ISEOZ30SybflPJa7MgS~rppWtl-zCMW0nd6L2LwufKw3l-qgtjQal~SRuwKJQOwZ7E3HfUg__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA][pdf]]) con [[https://www.santannapisa.it/en/giovanni-dosi][Giovanni Dosi]] (che è tipo uno suuuper importante a Sant'Anna) su
agent-based models per macroeconomia. Interessante.

** [[https://www.santannapisa.it/it/daniele-giachini][Daniele Giachini]]
Lui non è troppo importante ed è quasi economista classico. Nonostante questo fa molte cose numeriche e collabora con gente figa (tipo [[Andrea Vandin]] in [[https://arxiv.org/pdf/2509.10977][questo paper]])

Una cosa che può sembrare molto figa è tipo [[https://arxiv.org/pdf/2507.13767][questo paper su Opinion Dynamics]]:
#+begin_quote
In this work we introduce a new model of lobbying-driven opinion
influence within opinion dynamics, where lobbyists can implement complex strategies and are characterised by a finite budget.
#+end_quote

* IMT

** Andrea Vandin
Scrivigli che è interessante. Fa informatica teorica ma poi applica pure in qualche modo. [[https://arxiv.org/pdf/2601.10224][Qui]] un esempio di come applica.

Interessante che faceva compiler construction prima di Alceste Scalas.
