#+STARTUP: overview
#+STARTUP: indent

* Vienna - [[https://csh.ac.at/][Complexity Science Hub]]
** [[https://csh.ac.at/research/research-topic/social-complexity-collapse/][Social Complexity & Collapse]]
Ha a che fare con *Storia*.
*** [[https://peterturchin.com/][Peter Turchin]] [[https://scholar.google.com/citations?hl=en&user=W0C05zIAAAAJ&view_op=list_works&sortby=pubdate][(scholar]])
È il capo. Super importante ([[https://en.wikipedia.org/wiki/Peter_Turchin][wikipedia]], h-index 75), ha /fondato/ questa cosa che chiama /cliodynamics/, fa database di storia/archeologia.

Nel gruppo ci sta altra gente:
*** [[https://mariadelriochanona.info/][Maria del Rio-Chanona]] ([[https://scholar.google.com/citations?user=HwK5iiEAAAAJ&hl=en][scholar]])
Sta in realtà ad [[https://profiles.ucl.ac.uk/97689-maria-del-riochanona][UCL]]. È una matematica, fa cose di questo tipo ma usando molto AI, NLP. Studia tipo impatto di AI. [[https://ucl-epsrc-dtp.github.io/2026-27-project-catalogue/projects/2531bd1646.html][Sta cercando un dottorato]] per AI/Multi-agent systems.
Sembra faccia tipo come la storia si sta evolvendo con AI. Una cosa del genere.
*** [[https://csh.ac.at/james-bennett/][James Bennett]] (scholar non si trova...)
Non si capisce bene che fa, ma è interessante perché ha tipo lanciato lui il netflix prize (????)

Poi ci stanno dei
*** PhD
- [[https://csh.ac.at/harry-fox/][Harry Fox]] è un tipo, applica concetti della fisica a /economia, sociologia e psicologia di gruppo/. Interessante...
** [[https://csh.ac.at/research/research-topic/collective-minds/][Collective Minds]]
Questo è forse anche più interessante. La descrizione è carina, la incollo...
:Descrizione:
Currently, we are lacking a solid scientific paradigm for studying
collective adaptation. Instead, its intertwined cognitive and social
dimensions have been studied in relatively isolated disciplines. We
bring these dimensions together in computational models grounded in
real-world data on cognition and sociality.
:END:
Fanno (mi sembra) cose al limite tra psicologia, sociologia e scienze dure.

Ci sono 2 capi
*** [[https://www.olssonresearch.com/][Henrik Olsson]] ([[https://scholar.google.com/citations?user=XKwkvxcAAAAJ&hl=en][scholar]])
È psicologo, ma sembra essersi avvicinato abbastanza a ricerca
operativa. Sembra essere piuttosto interessante - approfondisci!
*** TODO Approfondisci questo sopra
*** PhD
- [[https://scholar.google.com/citations?hl=de&user=9FQdKwwAAAAJ&view_op=list_works&sortby=pubdate][Jula Lühring]] sembra abbastanza interessante - è PhD ma già ha un po'
  di citazioni ecc. Fa comunicazione, e cose su diffusione della
  disinformazione
* Sapienza
** [[https://chimera.roma1.infn.it/][Chimera]] (fisica)
Questo in realtà non è ben chiaro se esistono ancora.
Sembrano molto molto fisici e ci sta Parisi di mezzo - quindi pericolo.

Vabbè fanno moltissimo fisica... Un po' troppo.
*** [[https://sites.google.com/uniroma1.it/irene-giardina][Irene Giardina]] ([[https://scholar.google.it/citations?user=lPBjU44AAAAJ&hl=it][scholar]])
Praticamente fa fisica applicata a sistemi viventi tipo, e /collective behavior/ loro.
Forse non molto interessante, ma abbiamo stesso cognome...
Sta nel gruppo [[https://www.isc.cnr.it/groups/cobbs/][Collective Behaviour in Biological Systems]] infatti.
** [[https://cdcs.di.uniroma1.it/][Center for Data Science and Complexity for Society]] (informatica)
Sicuramente fanno parecchio su polarizzazione. Che è interessante comunque.
Poi sembra facciano anche cose su LLM e forse sentiment analysis (che vorrei fare un po' meno).

Sembra che siano piuttosto applicati, forse un po' troppo. Mi fa un po' paura questa cosa della divulgazione.

/Where data meets complexity, and science informs society./ Boh

Il boss è
*** [[https://walterquattrociocchi.site.uniroma1.it/][Walter Quattrociocchi]] ([[https://scholar.google.it/citations?user=_OCIc6UAAAAJ&hl=en][scholar]])
È abbastanza uno importante, ha scritto libri ecc.
Fa ogni paper del gruppo. Ha fatto fortuna con covid e disinformazione.
* Tor Vergata
** Fisica
*** Giulio Cimini [[https://scholar.google.com/citations?hl=en&user=0uPPZ5sAAAAJ&view_op=list_works&sortby=pubdate][(scholar)]]
È piuttosto fisico, ma fa cose potenzialmente interessanti.

In particolare, [[https://scholar.google.com/citations?view_op=view_citation&hl=en&user=0uPPZ5sAAAAJ&sortby=pubdate&citation_for_view=0uPPZ5sAAAAJ:B3FOqHPlNUQC][qui]] esprimono quanto una società è /creditworth/ tramite le sue connessioni,
trattando come un valore il fatto di aver tante connessioni (tipo), e la cosa è che ci riescono!!
* Dauphine
Professori abilitati ad avere dottorati sono [[https://ecole-doctorale.dauphine.psl.eu/candidature/trouver-une-direction-de-these][qui]].
** [[https://www.lamsade.dauphine.fr/en/about-us/lamsade-in-brief.html][LAMSADE (Laboratoire d'Analyse et Modélisation des Systèmes et Aide à la Décision)]]
Questo è in origine centro di ricerca operativa, si è esteso a /aiuto alla decisione/.
Si possono trovare tante cose mi sa qui.
*** TODO André Rossi
*** [[https://www.lamsade.dauphine.fr/~lang/][Jérôme Lang]] ([[https://scholar.google.com/citations?hl=fr&user=cNgZXNcAAAAJ&view_op=list_works&sortby=pubdate][scholar]], [[https://fr.wikipedia.org/wiki/J%C3%A9r%C3%B4me_Lang][wikipedia]])
Ha taaante citazioni (h-index tipo 67), anche se è solo /directeur de recherche/.

È interessante: fa principalmente teoria del voto, ed intelligenza artificiale ma non statistica, precisa (a quanto sembra).

La cosa che fa si chiama tipo /computational social *choice*/.
#+begin_quote
/Social choice studies the behavior of different mathematical procedures (social welfare functions) used to combine individual preferences into a coherent whole/.

È tipo la scienza di come le società prendono decisioni ma, in contrasto alle scienze politiche,
prova a modellizzare processi ottimali piuttosto che a descrivere i processi attuali.

Nata da [[https://www.jstor.org/stable/j.ctt1nqb90][questo libro]] del 1951. Il libro è suuuper interessante!!
#+end_quote

È molto interessante l'impatto che la sua ricerca può potenzialmente avere sul mondo, sono *molto molto* interessato.
*** [[https://sites.google.com/site/ridalaraki/][Rida Laraki]] ([[https://scholar.google.com/citations?hl=fr&user=zwkQWEgAAAAJ&view_op=list_works&sortby=pubdate][scholar]])
Mi sa che in realtà sta in Marocco... Ma è abilitato a dirigere PhD a Dauphine (?).

Comunque è interessante: ha master e PhD in matematica (non so che matematica...), e fa teoria dei giochi, ricerca operativa e pure lui /social chioce/.

È molto famoso per questa un metodo di voto che ha inventato con [[https://en.wikipedia.org/wiki/Michel_Balinski][un matematico molto importante]], chiamato [[https://en.wikipedia.org/wiki/Majority_judgment][majority judgement]].
Questo sembra una cosa interessante, ma non interessantissima - non molto complessa probabilmente, anche se non ho letto il libro loro.

Comunque queste cose che presumono che tutti gli elettori siano razionali ecc non possono mai funzionare.
Addirittura lui ha fatto un'estensione di questo sistema che permette di esprimere /incertezza/ sulla valutazione del candidato.
Secondo me assolutamente nessuno userebbe questa incertezza.

*** [[https://www.lamsade.dauphine.fr/~moretti/][Stefano Moretti]] ([[https://scholar.google.com/citations?hl=it&user=wQOB0vkAAAAJ&view_op=list_works&sortby=pubdate][scholar]])
Scrivigli perché è molto interessante. Lavora abbastanza in teoria dei giochi (ha fatto tipo 2 dottorati in teoria dei giochi).
Pubblica in giornali abbastanza sfigati sembra.
Ha un approccio abbastanza formale e lavora con ordini.

*** [[https://sites.google.com/site/julienlesca/home][Julien Lesca]] ([[https://scholar.google.com/citations?user=iNznokkAAAAJ&hl=fr][scholar]])
Interessante: è un informatico, e fa proprio cose di /decision science/ (se questo vuol dire qualche cosa).
Fa pure cose con grafi e ottimizzazione. Solo che pubblica poco, questa cosa non si capisce tanto.

Nota che, in [[https://www.ifaamas.org/Proceedings/aamas2022/pdfs/p687.pdf][questo paper]], dice che
#+begin_quote
We study a student-project allocation problem motivated by the real
procedure used at the computer science department of University
Paris-Dauphine. The institute (school, university) publishes a set
of PhD projects
#+end_quote
Questo è un po' strano (non mi risulta...). Forse glielo si può chiedere.
*** [[https://dauphine.psl.eu/recherche/cvtheque/profil/grigori-daniela][Daniela Grigori]] ([[https://scholar.google.com/citations?hl=fr&user=uOpbfVsAAAAJ&view_op=list_works&sortby=pubdate][scholar]])
Fa cose interessanti, anche se sembra un po' in decadenza.
È stata direttrice del LAMSADE fino al 2023.

Fa grafi e cose con processi aziendali.
È informatica, può essere interessante.
*** [[https://www.lamsade.dauphine.fr/~mlampis/][Michael Lampis]] ([[https://scholar.google.com/citations?user=x0XUqygAAAAJ&hl=en][scholar]])
È abbastanza un informatico puro (studia complessità asintotica e cose del genere),
ma la cosa interessante è che lavora molto con i grafi. Che sono abbastanza interessanti. Però praticamente non lavora su applicazioni.

Se gli scrivessi dovrei scrivergli ciao mi interessa quello che fai mi dici un applicazione?
*** Gente varia
Se serve gente che fa ottimizzazione discreta/lavora su grafi c'è di tutto:
[[https://dauphine.psl.eu/recherche/cvtheque/profil/aissi-hassene][Hassan Aissi]], [[https://dauphine.psl.eu/recherche/cvtheque/profil/bazgan-cristina][Cristina Bazgan]].
[[https://dauphine.psl.eu/recherche/cvtheque/profil/harutyunyan-ararat][Harutyunyan Ararat]] lavora su grafi in maniera molto teorica.

C'è pure parecchia gente che fa AI:
ad esempio, [[https://www.lamsade.dauphine.fr/~ychevaleyre/][Yann Chevaleyre]] ha un PhD aperto (in /robustness in AI/).
* Sciences po
Chiaramente qui è più difficile, sono estremamente nella parte qualitativa... Però forse qualcosa ci sta.
** [[https://www.sciencespo.fr/cdsp/en/][Centre for Socio-Political Data]]
Sono quelli che gestiscono dati in generale. Per quello che ho capito fanno diverse cose:
- Gestiscono tutta l'infrastuttura di sciences po (anche sito web?) (ma questo non è che sono proprio sicuro).
- Assistono la ricerca varia tramite produzione di dati (ci sono un sacco di questi /ingegneri di ricerca/).
- Fanno ricerca.

[[https://www.sciencespo.fr/cdsp/en/news/post-doctoral-researcher-in-historic-political-data-analysis-2-year-contract/][Stanno cercando un postdoc]], finanziato da Open AI (???). Sicuramente se volessero potrebbero prendere un PhD, ma mi sa che non vogliono qualcuno di solo scientifico.

In generale, hanno tutti background in scienze politiche tranne poche eccezioni.
[[https://www.sciencespo.fr/cdsp/en/who-are-we/team/][Qui]] c'è tutta la gente.

*** [[https://www.sciencespo.fr/cdsp/fr/qui-sommes-nous/equipe/mahendra-paipuri/][Mahendra Paipuri]] ([[https://scholar.google.com/citations?hl=en&user=6kCpWZ8AAAAJ&view_op=list_works&sortby=pubdate][scholar]])
Scrivigli assolutamente. Ha lavorato nel traffico ed ha pubblicato con Nikolas Geroliminis.
Ora non si capisce bene che fa (in realtà dice /dirige la squadra dei progetti numerici/, ma è strano dato che ha un dottorato comunque),
ma sta nella squadra.

Questo va raggiunto assolutamente.

*** [[https://www.emilianogrossman.eu/][Emiliano Grossman]] ([[https://scholar.google.com/citations?hl=en&user=mhVGOysAAAAJ&view_op=list_works&sortby=pubdate][scholar]])
È il capo del gruppo. Dalla ricerca che fa sembra faccia cose molto umanistiche, ma è comunque direttore del centro per i dati...

Fa ricerca su partiti, elezioni, ecc.

*** [[https://www.rovny.org/][Jan Rovny]] ([[https://scholar.google.fr/citations?hl=fr&user=ElGAc6MAAAAJ&view_op=list_works&sortby=pubdate][scholar]])
Lui sembra faccia un po' più ricerca con dati, anche se non sembra avere nessun'affiliazione con il CDSP
(nel sito dice che è affiliato ad un altro centro, il [[https://www.sciencespo.fr/centre-etudes-europeennes/en/][Centre for European Studies and Comparative Politics]]).

In effetti, fa ricerca sui partiti e la politica europea.

*** [[https://www.sciencespo.fr/centre-etudes-europeennes/en/directory/sattelmayer-luis/][Luis Sattelmayer]]
È un PhD, e lavora sul declino dei partiti tradizionali. La cosa interessante è che
/he primarily uses computational and experimental methods to examine party discourse and to find new ways of measuring party positions and party behavior/.

Non mi svolterà cose, ma magari ha contatti ecc.
* [[https://www.santannapisa.it/it][Sant'Anna]]
Il PhD si divide in 2: uno [[https://www.santannapisa.it/it/formazione/international-doctoral-programme-economics][in economia]], con scadenza il 15 aprile, ed [[https://www.santannapisa.it/it/formazione/phd][i restanti]], con scadenza 15 maggio.

A quanto pare questi sono quelli forti forti in economia dell'innovazione.

Quelli che scadono a maggio non sembrano molto interessanti, mentre quello in economia sembra una cosa figa.
Sarebbe super saggio parlare con qualcuno di economia. Il /Faculty Board/ (qualunque cosa voglia dire) sta [[https://www.santannapisa.it/it/coordinator-and-faculty-board-phd-economics][qui]].
** [[https://sites.google.com/view/alessiomoneta][Alessio Moneta]] [[https://scholar.google.it/citations?user=ORWa37UAAAAJ&hl=it][(scholar)]]
Lui sembra forse il più figo. Lavora molto su causalità, fa causal inference.

È il responsabile del programma di PhD (che può essere un pro o un contro per scrivergli, sarà meno curioso ma più pertinente forse.

È filosofo (??), e fa cose super tecniche.

** [[https://sites.google.com/view/giorgiofagiolo/home][Giorgio Fagiolo]] [[https://scholar.google.it/citations?user=B7N-yQIAAAAJ][(scholar)]]
Sembra uno importante, ma non ha posizioni particolari (è ordinario comunque).

La ricerca sembra parecchio interesante, fa molto numerico. È tipo statistico. Anche lui fa parecchio finanza, più che modellizzazione economica.

Ha lavorato a BETA magari conosce Nathalie (in realtà non so, BETA sembra una cosa grande proprio).

Suo paper più citato, [[https://www.iris.sssup.it/bitstream/11382/103287/1/SCIENCE_2009.pdf][Economic Networks: The New Challenges]], è fatto con [[https://www.unibocconi.it/en/faculty/fernando-vega-redondo][Fernando Vega-Redondo]], che mi hanno indicato a Siviglia!

** [[https://www.cafed.santannapisa.it/~giulio/][Giulio Bottazzi]] [[https://scholar.google.com/citations?user=WJaCqaQAAAAJ&hl=en][(scholar)]]
È un fisico, il problema è che fa abbastanza finanza. Ma dice /economic geography/ (che è molto figo, lo scrive [[https://www.santannapisa.it/it/giulio-bottazzi][qui]]) e tante altre cose fighe.

Probabilmente fa un po' troppa finanza.

Cosa interessante è che organizza, assieme a [[*\[\[https://www.santannapisa.it/it/daniele-giachini\]\[Daniele Giachini\]\]][Daniele Giachini]], la [[https://indico.sns.it/event/105/][Summer School of Mathematics for Economic and Social Sciences]].

Sembra sia uno molto serio a livello di matematica, magari sono un po' meno interessanti le cose che fa.
** [[https://www.santannapisa.it/it/andrea-roventini][Andrea Roventini]]
Lui mi sa che è abbastanza economista classico. Dice però che i suoi interessi sono tipo
#+begin_quote
complex system analysis, agent-based computational economics...
#+end_quote
e poi tutte cose normali.

Ha scritto [[https://www.cambridge.org/core/elements/abs/agentbased-macroeconomics/B7016A5CEE59694A420AF51A1347F00E][un libro carino]] ed [[https://www.sciencedirect.com/science/article/abs/pii/S016518891000148X][un paper]] ([[https://d1wqtxts1xzle7.cloudfront.net/44382174/2008-21-libre.pdf?1459761754=&response-content-disposition=inline%3B+filename%3DSchumpeter_meeting_Keynes_A_policy_frien.pdf&Expires=1774441495&Signature=RMk1zWbIHnkgxQOoqEMCXKbCwqAe~qsOWhL5GGTwUWmPDkIUdmnt~~JBqmOWvdVLULI6GF5rJRpOsUTdqeQB~jCqyUULSXd1IGkBttuu9WENQug574YzjvmYBvTfUqy-aw~3ACttqF4eZl6~H0JBe8c0JunXPSon6GEKateMLjcIUMZDrllOrtxg6ykcZiPCA0dxCQJLP9xBAibRcC-gYG-t9lh~eMJ3HQvZrLpBl1KWno8oWJuYeMcUdFgbBZTJivhuxLSkPhYy5H1ISEOZ30SybflPJa7MgS~rppWtl-zCMW0nd6L2LwufKw3l-qgtjQal~SRuwKJQOwZ7E3HfUg__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA][pdf]]) con [[https://www.santannapisa.it/en/giovanni-dosi][Giovanni Dosi]] (che è tipo uno suuuper importante a Sant'Anna) su
agent-based models per macroeconomia. Interessante.

** [[https://www.santannapisa.it/it/daniele-giachini][Daniele Giachini]]
Lui non è troppo importante ed è quasi economista classico. Nonostante questo fa molte cose numeriche e collabora con gente figa (tipo [[Andrea Vandin]] in [[https://arxiv.org/pdf/2509.10977][questo paper]])

Una cosa che può sembrare molto figa è tipo [[https://arxiv.org/pdf/2507.13767][questo paper su Opinion Dynamics]]:
#+begin_quote
In this work we introduce a new model of lobbying-driven opinion
influence within opinion dynamics, where lobbyists can implement complex strategies and are characterised by a finite budget.
#+end_quote

* [[https://www.imtlucca.it/homepage][IMT]]
In pratica ci sono 2 dottorati interessanti, uno di economia ([[https://eads.imtlucca.it/][EADS, Economics, Analytics and Decision Sciences]]) ed uno di /system science/ ([[https://sys.imtlucca.it/sysimt-school][Sys]]) (qualunque cosa voglia dire...).

Economia scade il <2026-06-06 sab>, system science il <2026-05-26 mar>.

** [[https://eads.imtlucca.it/][EADS]] ([[https://www.imtlucca.it/sites/default/files/2026-02/PhD%20call%20for%20applications%2026-27.pdf][bando]])

[[https://eads.imtlucca.it/faculty][Qui]] stanno le persone.

*** [[https://sites.google.com/site/enniobilancini/home][Ennio Bilancini]] [[https://scholar.google.com/citations?hl=en&user=PegYsyoAAAAJ&view_op=list_works&sortby=pubdate][(scholar)]]
È il coordinatore del phd. È piuttosto interessante: dice che fa /evolutionary game theory/ e /behavioural economics/.
In realtà fa tutte cose strane, apparentemente non troppo connesse. Che potrebbe essere /behavioural economics/ in realtà.

Sembra piuttosto lanciato: ha scritto da poco (2024) un paper con *Acemoglu* (???) ed un nature qualcosa.

[[https://drive.google.com/file/d/1jmJ6ZMkFGTadJVVaBeinJ6DnKnkcqDtm/view][Sul suo sito]] ha tutti paper in pdf.

Vediamo esempi:

**** [[https://drive.google.com/file/d/1jmJ6ZMkFGTadJVVaBeinJ6DnKnkcqDtm/view][Strategy Assortativity and the Evolution of Parochialism]]
Interessante: studia una società in cui la gente collabora o non collabora. È tipo un prisoner's dilemma sociale.
In generale, mi sa che è un prisoner's dilemma sociale tutta la letteratura su questo /parochialism/.

*** [[http://cse.lab.imtlucca.it/~mirco.tribastone/][Mirco Tribastone]] [[https://scholar.google.com/citations?hl=en&user=OKbh37IAAAAJ&view_op=list_works&sortby=pubdate][(scholar)]]
Non si capisce bene perché sta nel dottorato di economia. Se è un errore ok, sennò ha senso che lo contatto e vedo che dice.

È informatico, abbastanza tosto sembra. Fa però cose che stanno al limite tra informatica e ricerca operativa.
Se fosse nel dottorato di economia per ricerca operativa sarebbe molto interessante. Lavora molto con reti pure.

** [[https://sys.imtlucca.it/sysimt-school][Sys]] 
I professori (di tutto il PhD) sono [[https://sys.imtlucca.it/faculty][qui]]. Il coordinatore, [[http://cse.lab.imtlucca.it/~bemporad/][Alberto Bemporad]], nemmeno lo scrivo perché è proprio uno che fa controllo controllo. Ha un h-index assurdo (92???).

Sys ha 4 tracce. Quella che mi interesserebbe è [[https://sys.imtlucca.it/program-overview/complex-systems-and-networks-cn][Complex Systems and Networks]], che corrisponde al gruppo di ricerca [[https://networks.imtlucca.it/][NETWORKS]].
I professori del gruppo sono [[https://networks.imtlucca.it/people][qui]], nel board del PhD ci sono, tra quelli, tutti e soli quelli al primo gruppo (/Professors/, senza /assistant/).

Sono tutti fisici, ma ad es [[*\[\[https://www.imtlucca.it/anna.gallo\]\[Anna Gallo\]\] \[\[https://scholar.google.com/citations?user=Us0nqC8AAAAJ&hl=en\]\[(scholar)\]\]][Anna Gallo]] è matematica, quindi non disprezzano.
Disprezzeranno ingegneri, ma vabbè.

*** [[https://www.imtlucca.it/anna.gallo][Anna Gallo]] [[https://scholar.google.com/citations?user=Us0nqC8AAAAJ&hl=en][(scholar)]]
Moolto interessante, ma è una studentessa. Ci sono capitato 6000 volte, penso faccia cose proprio interessanti.
È matematica (triennale, magistrale). Mi ha accennato di questo [[https://www.imtlucca.it/massimo.riccaboni][Massimo Riccaboni]].

*** [[https://networks.imtlucca.it/people/tiziano][Tiziano Squartini]] [[https://scholar.google.com/citations?hl=en&user=-tMSEmwAAAAJ&view_op=list_works&sortby=pubdate][(scholar)]]
Fisico, fino al PhD. È stato postdoc di [[*\[\[https://networks.imtlucca.it/people/diego\]\[Diego Garlaschelli\]\] \[\[https://scholar.google.it/citations?user=G-WPCrMAAAAJ&hl=it&authuser=1\]\[(scholar)\]\]][Garlaschelli]].
Lavora praticamente solo su reti, il suo sito dice
#+begin_quote
His research interests lie at the intersection between statistical physics and graph theory, both on the theoretical and the applied side
#+end_quote

Due punti di contatto interessanti, piuttosto con tesi triennale che altro:
- [[https://arxiv.org/pdf/2603.12417][Questo paper]], dove usa le connessioni di una società come misura della sua /credit-worthiness/.
  Qui il contatto non è che ci sia più di tanto, ma dicono che fanno /certificazioni topologiche/, che in realtà è abbastanza vero.
- [[https://www.nature.com/articles/s42005-025-02182-2][Qui]], considerano, al posto di reti, ipergrafi (nei quali gli edges sono in realtà elementi dell'insieme delle parti).
  Cosa interessante è che dice che complessi simpliciali sono spesso utilizzati per rappresentare strutture più ricche delle reti normali.
  Io di complessi simpliciali me ne intendo! (più o meno). In realtà non fanno che tipo generalizzare la creazione di grafi random.
  #+begin_comment
  La differenza tra complesso simpliciale e ipergrafo penso sia semplicemente che in un complesso simpliciale,
   se il simplesso ABC è presente, lo sono anche i simplessi AB, BC, AC. Negli ipergrafi no.
#+end_comment


*** [[https://networks.imtlucca.it/people/diego][Diego Garlaschelli]] [[https://scholar.google.it/citations?user=G-WPCrMAAAAJ&hl=it&authuser=1][(scholar)]]
Lui è il direttore del gruppo. È abbastanza il pezzo forte.

Anche lui fisico, sembra lavori su reti o su random graph models.

** Andrea Vandin
Scrivigli che è interessante. Fa informatica teorica ma poi applica pure in qualche modo. [[https://arxiv.org/pdf/2601.10224][Qui]] un esempio di come applica.

Interessante che faceva compiler construction prima di Alceste Scalas.

* Ca' Foscari [[https://www.unive.it/web/it/259/bando-annuale][(bando)]]
Hanno PhD che scade il 6 maggio.
Direttore di PhD è coautore di [[*\[\[https://www.cafed.santannapisa.it/~giulio/\]\[Giulio Bottazzi\]\] \[\[https://scholar.google.com/citations?user=WJaCqaQAAAAJ&hl=en\]\[(scholar)\]\]][Bottazzi]], ma c'è anche altro di interessante.

** Direttori PhD
*** [[https://pdedindo.github.io/index.html][Pietro Dindo]] [[https://scholar.google.com/citations?hl=en&user=HxKn6dcAAAAJ&view_op=list_works&sortby=pubdate][(scholar)]]
Direttore del programma, nonché coautore di [[*\[\[https://www.cafed.santannapisa.it/~giulio/\]\[Giulio Bottazzi\]\] \[\[https://scholar.google.com/citations?user=WJaCqaQAAAAJ&hl=en\]\[(scholar)\]\]][Bottazzi]].

Fa sempre modellizzazione, ma mi sembra un po' utopistica:
ad es, in [[https://iris.unive.it/bitstream/10278/5100127/1/ssrn-4786867.pdf][questo paper]], tratta l'/acculturazione/ come una cosa super precisa, e sviluppa un framework teorico per studiarla.
Mi sembrerebbe abbastanza interessante, se effettivamente si riuscissero a modellare fenomeni reali così. Ma mi sembra tutto un po' troppo astratto per farlo!

Sembra essere l'esatto opposto del claim di Maria che l'economia è una scienza sociale.
*** [[https://sites.google.com/site/lorenzobastianello/][Lorenzo Bastianello]]
È statistico, fa decision theory. PhD in /applied mathematics/, secondo lui.
#+begin_center
Per /decision theory/, [[https://media.longnow.org/files/2/REVIVE/Advances%20in%20prospect%20theory.pdf][questo paper]] sembra importantissimo (spoiler lo è), e molto interessante!
#+end_center

Fa cose molto interessanti, anche se non ne capisco benissimo le applicazioni:
in [[https://arxiv.org/pdf/2602.06672][questo working paper]], cerca topologie che rendano continue determinate applicazioni tipo.
Pure [[https://drive.google.com/file/d/1oGkgI3LJRgDu5UAyOZmp7kfWzyYdVkM0/view][questo]] è abbastanza interessante: praticamente fanno cose in utility theory (come un individuo percepisce una vincita o una perdita),
studiando casi di questa [[https://en.wikipedia.org/wiki/Cumulative_prospect_theory][Comulative Prospect Theory]].

Collabora con questo [[https://sites.google.com/view/jjoc/home?authuser=0][Jaime Orillo]] che sta in Brasile ma è interessante - è un matematico e fa tipo topologia in scienze sociali (??)

*** [[https://mlicalzi.github.io/][Marco Li Calzi]] [[https://scholar.google.com/citations?hl=it&user=BRTQX8gAAAAJ&view_op=list_works&sortby=pubdate][(scholar)]]
È economista, ma fa sostanzialmente matematica applicata a scienze sociali.
In realtà, il suo campo è /decision sciences/. Ha avuto visiting sia a IMT che a Dauphine.

Il suo [[https://arxiv.org/pdf/2603.12958][paper più recente]] è abbastanza interessante, ho scritto delle idee [[file:idee_ricerca/li_calzi_grading/grading.org::+bibliography: grading.bib][qui]].

Sembra non faccia econometria praticamente. Interessante direi.

*** [[https://sites.google.com/view/robertocasarin][Roberto Casarin]] [[https://scholar.google.com/citations?hl=it&user=5bEU2N4AAAAJ][(scholar)]]
Interessante, anche se le applicazioni sue sono principalmente finanza.
Ma sempre che descrive il mondo comunque se vedi!

È molto serio in matematica, fa tutte cose tipo all'intersezione tra Catene di Markov e Analisi Bayesiana (che vuol dire, molto statistica).
Se vedi però sono cose piuttosto interessanti.
Fa molto ad esempio questi *Markov Switching Models*.

Probabilmente gli posso scrivere che se dovessi chiedere di nuovo la tesi magistrale gli chiederei quello:
è molto interessante, ma scrivere un progetto su cose sue lo vedo un po' tosto.
** [[https://www.unive.it/data/11644/][Research Institute for Complexity]]
*** [[https://www.guidocaldarelli.com/][Guido Caldarelli]] ([[https://scholar.google.com/citations?user=RZid9X8AAAAJ&hl=it][scholar]], [[https://en.wikipedia.org/wiki/Guido_Caldarelli][wikipedia]])
Lui super importante. È fisico, ha studiato a Sapienza, PhD a SISSA, prof a IMT.
È direttore dell'[[https://www.isc.cnr.it/][istituto dei sistemi complessi al CNR]].
È molto interessante per il mix tra teorico ed applicato, che sembra giusto.
Il problema è che non posso scrivergli haha. Dovrebbe stare a Roma (CNR) però.
* [[https://www.ssmeridionale.it/modeling-and-engineering-risk-and-complexity-merc-2/][Scuola Superiore Meridionale]]
